

// SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

// SIGN OUT
export const SIGNOUT_SUCCESS = "SIGNOUT_SUCCESS";
export const SIGNOUT_ERROR = "SIGNOUT_ERROR";

// COMMON
export const SET_LOADING = "SET_LOADING";
export const SET_ALERT = "SET_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

// PRODUCTS
export const SET_PRODUCTS_SUCCESS = "SET_PRODUCTS_SUCCESS";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";

// PRODUCT
export const SET_PRODUCT_SUCCESS = "SET_PRODUCT_SUCCESS";
export const SET_PRODUCT_ERROR = "SET_PRODUCT_ERROR";


export const FETCH_ALL_BLOGS = 'FETCH_ALL_BLOGS';
export const FETCH_BLOG = 'FETCH_BLOG';
export const SET_USER = 'SET_USER';
export const SET_LOADING_STATUS = 'SET_LOADING_STATUS';


export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const GET_PRODUCT_UPDATE = 'GET_PRODUCT_UPDATE';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';

export const SHOW_ALERT = 'SHOW_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

